---
- name: Setup Netbox (install/upgrade)
  hosts: netbox
  gather_facts: true
  become: true
  tasks:
    - name: Include netbox role
      ansible.builtin.include_role:
        name: netbox
      vars:
        netbox_version: 4.0.7
        netbox_app_fqdn: 
        netbox_sync_host: 
        netbox_sync_vcenter_fqdn: 
        netbox_sync_version: "v1.6.1"
        netbox_sync_api_token:
        netbox_sync_vcenter_password:
        netbox_secret_key:
        netbox_db_password:
        netbox_ldap_proxy_pass:
        netbox_ldap_bind_dn:
        netbox_ldap_group_dn:
        netbox_ldap_active_group: 
        netbox_ldap_staff_group:
        netbox_ldap_superuser_group:

        netbox_ldap_user_search:
        netbox_ldap_group_search:
        netbox_napalm_username:
        netbox_napalm_password:
        netbox_https_dns_resolver:
