---
- name: install and configure initial netbox
  hosts: netbox
  become: true
  gather_facts: true
  tasks:
    - name: provide a postgresql installation
      include_tasks: tasks/setup-postgres.yml

    - name: make sure we have a superuser
      command: "{{ netbox_install_venv}}/bin/python3 /opt/netbox/netbox/manage.py createsuperuser"

- import_playbook: setup-nginx.yml
- import_playbook: setup-netbox.yml
