- name: install and configure nginx for netbox
  hosts: netbox
  become: yes
  gather_facts: yes
  tasks:
    - name: make sure we have nginx
      package:
        name: "{{ item }}"
        state: present
      loop:
        - nginx

    - name: remove default config
      file:
        state: absent
        path: "{{ item }}"
      loop:
        - /etc/nginx/sites-enabled/default
        - /etc/nginx/sites-available/default

    - name: deploy netbox webserver config
      template:
        src: "{{ netbox_app_fqdn }}.conf.j2"
        dest: "/etc/nginx/conf.d/{{ netbox_app_fqdn }}.conf"
        mode: '0640'
      notify: restart nginx

    - name: deploy certificate private key
      copy:
        src: cert/{{ netbox_app_fqdn }}
        dest: "{{ netbox_ssl_cert_private }}"
        owner: "{{ netbox_system_user }}"
        group: "www-data"
        mode: "0440"
      notify: restart nginx

    - name: deploy certificate
      copy:
        src: "cert/{{ netbox_app_fqdn }}.crt"
        dest: "{{ netbox_ssl_cert }}"
        owner: "{{ netbox_system_user }}"
        group: "www-data"
        mode: "0644"
      notify: restart nginx

    - name: deploy ca chain
      copy:
        src: cert/ca-chain.pem
        dest: "{{ netbox_ssl_ca_chain }}"
        owner: "{{ netbox_system_user }}"
        group: "www-data"
        mode: "0644"
      notify: restart nginx

    - name: make sure our services are running
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

